name       : python-zeroconf
version    : 0.17.6
release    : 1
source     :
    - https://pypi.python.org/packages/b8/15/d4b1773e91f8ff54681c3a0d45baec553ffa850f42beb62353156ab4a64c/zeroconf-0.17.6.tar.gz : b614baa73833bdfc8ae64f2a9f5d19b014ad3164fbbc8513ef27a7bbe1e6c5e3
license    : LGPL-2.1
component  : programming.python
summary    : A pure python implementation of multicast DNS service discovery
description: |
    A pure python implementation of multicast DNS service discovery
builddeps  :
    - python-enum34
    - python-netifaces
    - python-setuptools
    - python-six
rundeps    :
    - python-enum34
    - python-netifaces
    - python-six
build      : |
    %python_setup
    %python3_setup    
install    : |
    %python_install
    %python3_install
