name       : python-zeroconf
version    : 0.80.0
release    : 13
source     :
    - https://github.com/python-zeroconf/python-zeroconf/archive/refs/tags/0.80.0.tar.gz : a666cf9d3d3a7289ba8d160ab5797fd03ed1004a8c32b5e27f2c2c9c841809db
homepage   : https://github.com/python-zeroconf/python-zeroconf
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A pure python implementation of multicast DNS service discovery
description: |
    A pure python implementation of multicast DNS service discovery.
builddeps  :
    - cython
    - python-async_timeout  # check
    - python-build
    - python-ifaddr         # check
    - python-installer
    - python-poetry
    - python-pytest-asyncio # check
    - python-pytest-cov     # check
    - python-wheel
rundeps    :
    - python-async_timeout
    - python-ifaddr
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export SKIP_IPV6=1
    %python3_test pytest -k 'not (test_close_multiple_times or test_launch_and_close)'
