name       : python-zeroconf
version    : 0.18.0
release    : 2
source     :
    - https://pypi.python.org/packages/ab/6a/1f9f78aeebe283417db2980b8f6b8b41be1144f568ab9cc3efe893cdec74/zeroconf-0.18.0.tar.gz : c2cbcd7c54fa078afba47ab0c2125f487fd8465d4d398a9a4a01122836202868
license    : LGPL-2.1
component  : programming.python
summary    : A pure python implementation of multicast DNS service discovery
description: |
    A pure python implementation of multicast DNS service discovery
builddeps  :
    - python-enum34
    - python-netifaces
    - python-setuptools
    - python-six
rundeps    :
    - python-enum34
    - python-netifaces
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
