name       : python-zeroconf
version    : 0.39.4
release    : 12
source     :
    - https://github.com/jstasiak/python-zeroconf/archive/refs/tags/0.39.4.tar.gz : 32783c9a583419abe7223ba199e2ddebe9533011caecf6a268852e0fbea1186a
homepage   : https://github.com/jstasiak/python-zeroconf
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A pure python implementation of multicast DNS service discovery
description: |
    A pure python implementation of multicast DNS service discovery.
builddeps  :
    - python-async_timeout  # check
    - python-ifaddr         # check
    - python-pytest-asyncio # check
rundeps    :
    - python-async_timeout
    - python-ifaddr
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export SKIP_IPV6=1
    %python3_test pytest3 -k 'not (test_close_multiple_times or test_launch_and_close)'
