name       : python-zeroconf
version    : 0.19.1
release    : 4
source     :
    - https://github.com/jstasiak/python-zeroconf/archive/0.19.1.tar.gz : ca8952a3eb04818dcb566e1344f2f15b5dd6d487770384651cdfae777d5eb848
license    : LGPL-2.1
component  : programming.python
summary    : A pure python implementation of multicast DNS service discovery
description: |
    A pure python implementation of multicast DNS service discovery
builddeps  :
    - python-enum34
    - python-mock
    - python-netifaces
    - python-pytest
    - python-setuptools
    - python-six
rundeps    :
    - python-enum34
    - python-netifaces
    - python-six
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-enum-compat-from-install_requires.patch
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test -v -k "not launch_and_close"
    popd

    pushd $PKG_BUILD_DIR/py3build
        py.test3 -v -k "not launch_and_close"
    popd
