name       : python-zeroconf
version    : 0.31.0
release    : 6
source     :
    - https://github.com/jstasiak/python-zeroconf/archive/refs/tags/0.31.0.tar.gz : 587c22fd2730f0ed42b6405afc754c177543e11631e21c142204750de1f29c4e
homepage   : https://github.com/jstasiak/python-zeroconf
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A pure python implementation of multicast DNS service discovery
description: |
    A pure python implementation of multicast DNS service discovery.
builddeps  :
    - python-ifaddr
    - python-netifaces
    - python-pytest-asyncio
    - python-six
rundeps    :
    - python-ifaddr
    - python-netifaces
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    SKIP_IPV6=1 pytest3 -v py3build/zeroconf/test.py -k 'not (test_close_multiple_times or test_launch_and_close)'
