name       : python-zeroconf
version    : 0.38.4
release    : 9
source     :
    - https://github.com/jstasiak/python-zeroconf/archive/refs/tags/0.38.4.tar.gz : 74ead61490a7573d1cab1e9e9ea6fe846be0843c4ddd55633788d4670837c0eb
homepage   : https://github.com/jstasiak/python-zeroconf
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A pure python implementation of multicast DNS service discovery
description: |
    A pure python implementation of multicast DNS service discovery.
builddeps  :
    - python-ifaddr
    - python-netifaces
    - python-pytest-asyncio
    - python-six
rundeps    :
    - python-ifaddr
    - python-netifaces
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export SKIP_IPV6=1
    %python3_test pytest3 -k 'not (test_close_multiple_times or test_launch_and_close)'
